### PR TITLE
EIP-100

### PR DESCRIPTION
**Pull request by debris**
https://github.com/ethereum/EIPs/issues/100

### CODE REVIEW

**Comment by arkpar** [comment]
As far as I can see this implements EIP-100a. EIP-100b looks simpler and this is what go-ethereum implements.

**Comment by debris** [comment]
done

**Comment by arkpar** [comment]
For eip100b you don't really need to read and pass around uncle count. You can just check if `uncles_root` is empty or not in the header.

**Comment by debris** [comment]
you are absolutely right! I will close this one and create a new pr ;)

**Pull request closed without merging**
