### PR TITLE
Guanqun add unit tests

### PR DESCRIPTION
**Pull request by gavofyork**

### CODE REVIEW

**Comment by gavofyork** [comment]
not building properly. @General-Beck ?

**Comment by guanqun** [comment]
I used `cargo test -p ethjson` and it worked fine locally. What's the issue? I see "All checks have passed" from CI.

**Comment by rphmeier** [comment]
@guanqun https://gitlab.parity.io/parity/parity/builds/54720 indicates that the build was skipped because it modified no Rust files, which definitely isn't true.

**Comment by guanqun** [comment]
aha, I think I know the problem, here's the fix for it. https://github.com/paritytech/parity/pull/5668/commits/14b715bdc7e746801ed4e83af8654445d2d7366b

The original script only detects for "^js", interesting enough, I'm modifying "json"...

But I don't have permission to push to `guanqun-add-unit-tests`, probably someone can cherry-pick this commit.

**Comment by arkpar** [comment]
This is really great, thanks a lot!

**Pull request merged**
