### PR TITLE
Use associated type M::Error instead of Error

### PR DESCRIPTION
**Pull request by kseo**

### CODE REVIEW

**Comment by debris** [comment]
[clabot:check]

**Comment by debris** [comment]
let's wait for clabot to wake up

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot: check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by kseo** [comment]
[clabot:check]

**Pull request merged**
