### PR TITLE
Add test for ethstore-cli, fixes #8027

### LINKED ISSUE #8027: add tests for ethstore-cli
to avoid issues like #8026

### PR DESCRIPTION
**Pull request by debris**
reopened #8107

### CODE REVIEW

**Comment by debris** [comment]
lol, idk why it keeps failing... I rebased and put it on a different branch and the result is the same... how is that possible? @paritytech/ci is it possible for you to check if there is something cached in this build?

In the logs I can see

```
[0Ksection_start:1521687819:restore_cache
[0K[32;1mChecking cache for test-pr-8187-2...[0;m
[32;1mSuccessfully extracted cache[0;m
section_end:1521687821:restore_cache
```

but idk what it means

**Comment by izgzhen** [comment]
I cloud actually produce similar error on my machine:

```
error: the crate `tiny_keccak` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`

error: the crate `ethereum_types` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`

error: the crate `ethbloom` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`

error: the crate `ethereum_types_serialize` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`

error: aborting due to 4 previous errors

error: Could not compile `ethabi-derive`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

by running `cargo build` on top-level.

**Comment by izgzhen** [comment]
But I can't reproduce it deterministically by repeating the same steps

**Comment by General-Beck** [comment]
``cargo check`` and next ``cargo test``

**Pull request merged**
