### PR TITLE
Update hidapi

### LINKED ISSUE #7542: Segmentation Fault on macOS 10.13.2 at start when enumerating hardware wallets
macOS version is 10.13.2 with Supplemental Update (17C205), running **on Hackintosh hardware**.

Tested on source-build `Parity/v1.10.0-unstable-f044b61f4-20180111/x86_64-macos/rustc1.23.0`.

Behavior replicates as well with nightly macOS release, and all variant releases from [homebrew-paritytech](https://github.com/paritytech/homebrew-paritytech).

Crash occurs before synchronization can begin.

Crash occurs regardless of network selected. (Tested all possible.)

Crash occurs repeatably every time `parity` is started.

Crash looks like this:

```
$ ./target/debug/parity
Loading config file from /Users/tsutsu/Library/Application Support/io.parity.ethereum/config.toml
2018-01-11 16:19:25  Starting Parity/v1.10.0-unstable-f044b61f4-20180111/x86_64-macos/rustc1.23.0
2018-01-11 16:19:25  Keys path /Volumes/Media/Blockchains/eth-ropsten/keys/Ropsten
2018-01-11 16:19:25  DB path /Volumes/Media/Blockchains/eth-ropsten/chains/test/db/ae90623718e47d66
2018-01-11 16:19:25  Path to dapps /Volumes/Media/Blockchains/eth-ropsten/dapps
2018-01-11 16:19:25  State DB configuration: fast
2018-01-11 16:19:25  Operating mode: passive
Segmentation fault: 11
```

`rust-lldb` reveals the following backtrace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00007fff29d6a328 CoreFoundation`CFSetGetCount + 24
    frame #1: 0x0000000103993865 parity`hid_enumerate(vendor_id=0, product_id=0) at hid.c:412
    frame #2: 0x000000010398aa8d parity`hidapi::{{impl}}::get_hid_device_info_vector at lib.rs:107
    frame #3: 0x000000010398a9b5 parity`hidapi::{{impl}}::new at lib.rs:91
    frame #4: 0x00000001037ab0c7 parity`hardware_wallet::{{impl}}::new at lib.rs:175
    frame #5: 0x0000000102533b8f parity`ethcore::account_provider::{{impl}}::new(sstore=Box<SecretStore> {
```

This looks like a problem in parity's [fork of the `hidapi-rs` crate](https://github.com/paritytech/hidapi-rs). Issues are closed there, so I'm opening one here instead.

As this issue hasn't been reported by any other macOS user, I'm guessing that this is caused by something weird and Hackintosh-related sitting in my device tree. Still a problem that might be encountered mysteriously by anyone else with such a configuration, though, so it'd be nice to get it fixed.

[This PR in `hidapi` looks related to this problem](https://github.com/signal11/hidapi/pull/359).

### Workarounds

Passing `--no-hardware-wallets` or setting `disable_hardware = true` in `config.toml` skips the broken part of the code, and parity starts successfully.

However, a segmentation fault still occurs on `SIGINT`:

```
^C2018-01-11 16:52:34  Finishing work, please wait...
Segmentation fault: 11
```

### Potential solutions

* urge @signal11 to merge the above PR, and then update the `hidapi` submodule reference in your `hidapi-rs` fork.
* more drastically, fork [hidapi](https://github.com/signal11/hidapi) itself, merge the PR above into your fork, and then update the `hidapi` submodule in your fork of `hidapi-rs` with your newly-forked `hidapi`.
* come up with some check equivalent to the one in the PR that could be done in `hidapi-rs` itself, and add it to your fork.

### PR DESCRIPTION
**Pull request by debris**
fixes #7542

### CODE REVIEW

**Comment by niklasad1** [comment]
Anyone that has tested that this solves the issue?

**Comment by debris** [comment]
It was reproducible only on Hackintosh. I know noone who has it, but the stack trace was quite obvious.

**Comment by Laziemo** [comment]
just tried compiling the latest release and get this hidapi error ((

d76:~/nodes/parity-ethereum-2.1.4$ RUST_BACKTRACE=1 cargo build --release --features final
 Downloading log v0.4.6
 Downloading lazy_static v1.2.0                                                                                                                                                                             
 Downloading byteorder v1.2.7                                                                                                                                                                               
 Downloading rayon v1.0.3                                                                                                                                                                                   
 Downloading cfg-if v0.1.6                                                                                                                                                                                  
 Downloading fixed-hash v0.2.5                                                                                                                                                                              
 Downloading syn v0.15.18                                                                                                                                                                                   
 Downloading quote v0.6.9                                                                                                                                                                                   
 Downloading tokio-io v0.1.10                                                                                                                                                                               
 Downloading memchr v2.1.1                                                                                                                                                                                  
 Downloading aho-corasick v0.6.9                                                                                                                                                                            
 Downloading utf8-ranges v1.0.2                                                                                                                                                                             
 Downloading ucd-util v0.1.2                                                                                                                                                                                
 Downloading tokio-threadpool v0.1.8                                                                                                                                                                        
 Downloading tokio-uds v0.2.3                                                                                                                                                                               
 Downloading tokio-fs v0.1.4                                                                                                                                                                                
   Compiling cfg-if v0.1.6                                                                                                                                                                                  
   Compiling rand_core v0.3.0                                                                                                                                                                               
   Compiling lazy_static v1.2.0                                                                                                                                                                             
   Compiling byteorder v1.2.7                                                                                                                                                                               
   Compiling rayon v1.0.3                                                                                                                                                                                   
   Compiling futures v0.1.25                                                                                                                                                                                
   Compiling proc-macro2 v0.4.20                                                                                                                                                                            
   Compiling serde v1.0.80                                                                                                                                                                                  
   Compiling lazycell v1.2.0                                                                                                                                                                                
   Compiling version_check v0.1.5                                                                                                                                                                           
   Compiling httparse v1.3.3                                                                                                                                                                                
   Compiling num-traits v0.2.6                                                                                                                                                                              
   Compiling gcc v0.3.55                                                                                                                                                                                    
   Compiling ucd-util v0.1.2                                                                                                                                                                                
   Compiling safemem v0.3.0                                                                                                                                                                                 
   Compiling rustc-hex v1.0.0                                                                                                                                                                               
   Compiling utf8-ranges v1.0.2                                                                                                                                                                             
   Compiling termcolor v1.0.4                                                                                                                                                                               
   Compiling mio-named-pipes v0.1.6                                                                                                                                                                         
   Compiling crossbeam-utils v0.2.2                                                                                                                                                                         
   Compiling log v0.4.6                                                                                                                                                                                     
   Compiling net2 v0.2.33                                                                                                                                                                                   
   Compiling thread_local v0.3.6                                                                                                                                                                            
   Compiling cmake v0.1.35                                                                                                                                                                                  
   Compiling eth-secp256k1 v0.5.7 (https://github.com/paritytech/rust-secp256k1#ccc06e74)                                                                                                                   
   Compiling rand_core v0.2.2                                                                                                                                                                               
   Compiling base64 v0.6.0                                                                                                                                                                                  
   Compiling parity-wasm v0.31.3                                                                                                                                                                            
   Compiling base64 v0.9.3                                                                                                                                                                                  
   Compiling regex-syntax v0.5.6                                                                                                                                                                            
   Compiling regex-syntax v0.6.2                                                                                                                                                                            
   Compiling unicase v2.2.0                                                                                                                                                                                 
   Compiling memchr v2.1.1                                                                                                                                                                                  
   Compiling unicase v1.4.2                                                                                                                                                                                 
   Compiling crossbeam-epoch v0.5.2                                                                                                                                                                         
   Compiling lock_api v0.1.4                                                                                                                                                                                
   Compiling bytes v0.4.10                                                                                                                                                                                  
   Compiling crossbeam-epoch v0.3.1                                                                                                                                                                         
   Compiling log v0.3.9                                                                                                                                                                                     
   Compiling trace-time v0.1.1                                                                                                                                                                              
   Compiling stats v0.1.0 (/home/eclassic/nodes/parity-ethereum-2.1.4/util/stats)                                                                                                                           
   Compiling hidapi v0.3.1 (https://github.com/paritytech/hidapi-rs#d4d32376)                                                                                                                               
   Compiling rand v0.5.5                                                                                                                                                                                    
   Compiling mio v0.6.16                                                                                                                                                                                    
   Compiling tokio-executor v0.1.5                                                                                                                                                                          
error: failed to run custom build command for `hidapi v0.3.1 (https://github.com/paritytech/hidapi-rs#d4d32376)`                                                                                            
process didn't exit successfully: `/home/eclassic/nodes/parity-ethereum-2.1.4/target/release/build/hidapi-7b8e690a779853db/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-Wall" "-Wextra" "-o" "/home/eclassic/nodes/parity-ethereum-2.1.4/target/release/build/hidapi-783de682732e743b/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c"
cargo:warning=etc/hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
cargo:warning= #include <libudev.h>
cargo:warning=          ^~~~~~~~~~~
cargo:warning=compilation terminated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-Wall" "-Wextra" "-o" "/home/eclassic/nodes/parity-ethereum-2.1.4/target/release/build/hidapi-783de682732e743b/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/eclassic/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:346
   7: cc::fail
   8: cc::Build::compile
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by niklasad1** [comment]
@Laziemo 
Have you installed `libudev-dev`? `libudev.h` is not in your path

**Comment by Laziemo** [comment]
Cheers @niklasad1  !
@joshua-mir helped figure this in another post. 
Thanks for the reply!

**Pull request merged**
