### PR TITLE
integrate ethabi into parity repo

### LINKED ISSUE #3380: Integrate ethabi
- [ ] Merge into parity repo;
- [ ] Use `uint` crate for uint/hash types.

### PR DESCRIPTION
**Pull request by guanqun**
Fixes #3380 's first task.

I decided to keep the commit history, so the that's why you see there are some previous commits from @debris 

The interesting commits from my side are:

- update the depedencies' path			57b1124
- resolve the multiple workspace error			b5b1814
- downgrade tiny-keccak to 1.0 and its changes			ac261ce
- add ethabi-cli to parity			527ed6a
- update Cargo.lock file			c61f926

I explicitly downgraded the `tiny-keccak`'s version in `ethabi`. Because I tried to run `cargo update`, but it hangs... 

I ran:
- `cargo build` and `cargo test`
- `./test.sh`
All seems fine.

### CODE REVIEW

**Comment by debris** [comment]
@gavofyork, I know that's a part of #3380, but given your yesterday's message about repo split is it still a thing we want to do?

**Comment by guanqun** [comment]
We're going to split the repo? Hmm, then it seems this is worthless... I should've asked you first.

Anyway I'll fix these issues in the next few days if we still want this.

**Comment by gavofyork** [comment]
carry on for now. the refactoring will be a much bigger job and it's not clear at this point where the repo splits are best made.

**Comment by debris** [comment]
This pr hasn't been updated for > 28 days and I'm closing it as a part of pull request cleanup. If it's still relevant, please rebase and reopen it.

**Pull request closed without merging**
