### PR TITLE
Remove NetworkContext::io_channel()

### PR DESCRIPTION
**Pull request by tomaka**
Method is unused.

### CODE REVIEW

**Comment by tomaka** [comment]
The tests fail at runtime on gitlab, which doesn't make sense considering the change.

**Comment by niklasad1** [comment]
Agree, `No space left on device (os error 28)` /cc @General-Beck

**Comment by 5chdn** [comment]
Need a secondary reviewer.

**Comment by 5chdn** [comment]
Thanks

**Pull request merged**
