### PR TITLE
Disable uncles by default

### PR DESCRIPTION
**Pull request by keorn**

### CODE REVIEW

**Comment by rstormsf** [comment]
:+1: merge!

**Comment by 5chdn** [comment]
This affects Kovan and all PoA, does it?

**Comment by keorn** [comment]
Kovan will stay the same, it just works for new chains. If one wants to keep running a chain with uncles they have to add `maximumUncleCount: 2` to the chain spec.

**Comment by debris** [comment]
How exactly is this value used? I can't see

**Comment by rstormsf** [comment]
#7065

**Comment by keorn** [comment]
@debris It determines the maximum number of uncles included in a block. Uncles are a fairly Ethash specific thing, so they should not be enabled by default.

**Pull request merged**
