### PR TITLE
backports to beta

### PR DESCRIPTION
**Pull request by debris**
#7282 - d5b81ead71a8c4b3eca5cc3dd18e575534cf73a6
#7368 - f3e7d94fc4112f81512593352450d3c6dc0a3033
#7412 - 67a74e155d00e76e9b03991b3310f24f99c855eb
#7421 - 9c0fceb1920731678ffc6248e197eb2dd19c872d
#7433 - 51319ebe3fa774b3008afa5f436ebdb28229a474
~~#7437 - 75f292154d2ab83b08af5876b863cc3104e3b813~~
#7476 - a553485bbd5e67adfcb90d94299ee944f1d90b98
#7451 - 33b8f28f6242afec9cbadc3f4861abe9b8813fcb
#7463 - 36e230ee165759e2a233e7511070a9c91ab6e106 
#7495 - 7316cb9d92bd193555d2206a3a0e12edc634020f
#7497 - 69d7c4f519e8f67025534815f85d035985f8e7a1
#7503 - ab7335d21d0f0c8e4b2f6c2eff04eb13fdd84c9b

### CODE REVIEW

**Comment by 5chdn** [comment]
We might want to hold on removing expanse for a second. Let's discuss this tomorrow.

**Comment by 5chdn** [comment]
To be backported after review:

- Expanse Byzantium update w/ correct metropolis difficulty increment divisor #7463
- Advance AuRa step as far as we can and prevent invalid blocks. #7451

**Comment by 5chdn** [comment]
Now only #7476 missing

**Comment by debris** [comment]
@5chdn done

**Comment by 5chdn** [comment]
Aaaand #7497 :)

**Comment by 5chdn** [comment]
And maybe #7503 ?

**Comment by andresilva** [comment]
LGTM!

**Pull request merged**
