### PR TITLE
Use `parity-react-scripts` for Wallet v1

### PR DESCRIPTION
**Pull request by ngotchac**
Use the `parity-react-script`package for `js-old` folder, ie. the v1 wallet.
The next steps would be to convert all the other dapps to use it as well, and change the way the UI gets build (would be simpler to just download the releases ZIP files, and put it in the build). The v1 wallet should IMO also be a dapp in a separate repo, not sure why it is still there.

[it actually deletes +/- 1,500 lines and adds +/- 309 lines ; numbers are big because of the lock files]

---
This change is [Reviewable](https://reviewable.io/reviews/paritytech/parity/7459)

### CODE REVIEW

**Comment by jacogr** [comment]
100% - v1 shouldn't really be in this repo anymore. (Remember it started as a "stopgap".) However, at this point in the 1.9 release cycle, I don't want to split it out.

**Comment by ngotchac** [comment]
Tests are failing because of linting issues : updated linting dependencies so some rules changed.
There is a separate PR to fix linting issues here: https://github.com/paritytech/parity/pull/7468

**Comment by jacogr** [comment]
Looks good. Let's just on-ice this until 1.9 is out. As discussed, I'm a bit cautious about making major changes this close to release. (Although technically, this should not affect anything, just want to keep the non-bug-fix changes to an absolute minimum)

**Comment by 5chdn** [comment]
Please resolve conflicts :)

**Comment by jacogr** [comment]
Can we re-open on https://github.com/Parity-JS/dapp-wallet

**Pull request closed without merging**
