### PR TITLE
Returns number of topcis to take fr..

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by debris** [comment]
thanks @jamesray1 . Please sign our CLA :)

**Comment by jamesray1** [comment]
[clabot:check]

**Comment by jamesray1** [comment]
Hey how did you integrate this CLA bot? Would be good to use it with https://github.com/Drops-of-Diamond/diamond_drops.

**Comment by debris** [comment]
@jamesray1 idk, it was in 2015. one of us followed the tutorial -> https://github.com/clabot/clabot

**Pull request merged**
