### PR TITLE
Fixed modexp gas calculation overflow

### PR DESCRIPTION
**Pull request by arkpar**

### CODE REVIEW

**Comment by gavofyork** [comment]
CI fails to build.

**Comment by arkpar** [comment]
That was a CI glitch. All passing now.

**Comment by gavofyork** [comment]
would need a link to the YP formula/EIP before this could reasonably be reviewed. might be worth getting martin @ EF to look over it, too.

**Comment by debris** [comment]
cc @holiman

**Comment by arkpar** [comment]
The code implements https://github.com/ethereum/EIPs/pull/198/files

**Comment by holiman** [comment]
Looks good to me!On Oct 13, 2017 3:23 PM, Marek Kotewicz <notifications@github.com> wrote:cc @holiman

**Pull request merged**
