### PR TITLE
Fixed broken link in README

### PR DESCRIPTION
**Pull request by shanev**

### CODE REVIEW

**Comment by shanev** [comment]
[clabot:check]

**Comment by 5chdn** [comment]
Thanks.

What happened to the ethcore docs?

**Comment by andresilva** [comment]
The wiki is also available at `https://wiki.parity.io/` not sure if we should link to that instead? The ethcore docs was it for Rust documentation?

**Comment by 5chdn** [comment]
Yeah we should

**Comment by 5chdn** [comment]
Thanks :)

**Pull request merged**
