### PR TITLE
Update light client hardcoded headers

### PR DESCRIPTION
**Pull request by Tbaut**
- Mainnet hardcoded headers until #5941249
- Ropsten hardcoded headers until #3612673
- Kovan hardcoded headers until #7690241

### CODE REVIEW

**Comment by 5chdn** [comment]
would be nice to have light headers for classic too, /cc @pyskell

**Comment by pyskell** [comment]
Excuse my ignorance, what are light headers?

**Comment by dvdplm** [comment]
This is hard to review without a better description with some context.

**Comment by 5chdn** [comment]
@dvdplm @pyskell the chainspec can contain hardcoded light headers. this allows the light client to sync from a "trusted" block rather than syncing from genesis. ref #8075

https://wiki.parity.io/FAQ#how-to-generate-a-new-hardcoded-sync-block-for-parity-light-client

**Comment by pyskell** [comment]
Got it, will get a PR ready soon.

**Comment by pyskell** [comment]
Almost done with this but light syncing seems to freeze:

- Occasionally hit a block where it stops syncing despite increased peer count
- After fully syncing it stops entirely
- Happens both with the default `--chain=classic` and my newly generated `--chain ./classic-lightsync.json` that I'm using to test. (https://paste.ee/p/gFxWu)
- Still on the right chain (ex. http://etherhub.io/block/6167953)
- Ctrl^C and restarting gets new blocks but then also stops at the new block.
- Happens with both `v1.11.6-beta-4ba600fcc-20180709` and `1.10.6`. Both were installed from the Debian AMD64 release debs you provide.

In both cases the output looks like this:
```
parity@parity-lightclient-syncing:~$ parity --light --chain classic-lightsync.json
2018-07-12 17:30:48 UTC Starting Parity/v1.11.6-beta-4ba600fcc-20180709/x86_64-linux-gnu/rustc1.27.0
2018-07-12 17:30:48 UTC Keys path /home/parity/.local/share/io.parity.ethereum/keys/Ethereum Classic
2018-07-12 17:30:48 UTC DB path /home/parity/.local/share/io.parity.ethereum/chains/classic/db/906a34e69aec8c0d
2018-07-12 17:30:48 UTC Path to dapps /home/parity/.local/share/io.parity.ethereum/dapps
2018-07-12 17:30:48 UTC Running in experimental Light Client mode.
2018-07-12 17:30:50 UTC Imported #6167920 0x74f2…243f (0.20 Mgas)
2018-07-12 17:30:54 UTC Syncing #6167953 0x065a…5e77     6 hdr/s      0+    0 Qed  #6167953    3/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:30:54 UTC Public node URL: enode://83b33409349ffa25e150555f7b4f8deebc68f3d34d782129dc3c8ba07b880c209310a4191e1725f2f6bef59bce9452d821111eaa786deab08a7e6551fca41f4f@178.128.9.152:30303
2018-07-12 17:30:59 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    4/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:31:09 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    4/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:31:29 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    5/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:31:44 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    5/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:31:54 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    5/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:32:04 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    6/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:32:14 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    6/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:32:24 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    5/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:32:44 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    5/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-07-12 17:32:49 UTC Syncing #6167953 0x065a…5e77     0 hdr/s      0+    0 Qed  #6167953    6/50 peers   23 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
```

Debug log: https://paste.ee/p/LoVM9

Going to try restarting from `block 0` with the new `classic-lightsync.json` and see if that fixes it.

**Comment by 5chdn** [comment]
@pyskell yeah this is a known issue, unfortunately, #6319. And, uh, also #6402 :(

What you can do is remove your nodes json and start again. Or just shut it down one day and continue at a later point. ETC probably does not have enough Parity nodes?

**Comment by sorpaas** [comment]
@pyskell For the one with problem, do you use the chain spec with hardcoded sync or without? I think if initially there're issues for light client to be on the right chain, what you can do is:

1. Sync a full node.
2. Start a light node, with `--reserved-only`, and `--reserved-peers` pointing to the full node. Restart the full node with `--reserved-peers` pointing to the light node.
3. Sync the light node and do export_hardcoded_sync.

**Comment by fckt** [comment]
Just for information why this is part of chainspec?
I was thinking that chainspec config is to describe consensus aware specification. Are these headers such?

**Comment by 5chdn** [comment]
> Just for information why this is part of chainspec?
> I was thinking that chainspec config is to describe consensus aware specification. Are these headers such?

I'm happy if you have a better idea. I had a similar question here when this was introduced. https://github.com/paritytech/parity/pull/8075#discussion_r177091317

**Comment by pyskell** [comment]
@sorpaas Thanks I will try that. I actually encounter this issue both with and without the `hardcodedSync`

The difference is:
`hardcodedSync` - Stops almost immediately after grabbing a few new blocks once we hit 3.1 million
without `hardcodedSync` - Stops periodically. I believe around blocks 2 and 5 million for me. Requires a restart and then continues.

@5chdn That is possible. I need to go through and test all of the nodes to see which are working and if any need replacing.

**Comment by pyskell** [comment]
Looks like it's working although I only get 2 peers. Is this because parity needs more bootnodes running recent versions of parity? Or is this just how light clients work?

Will make a PR.

**Comment by sorpaas** [comment]
@pyskell Light client has metering (https://github.com/paritytech/parity/blob/master/ethcore/light/src/net/request_credits.rs#L17), which may be one cause why you don't have many peers.

In the mean time, we definitely need more nodes (with recent versions)!

**Comment by fckt** [comment]
> I'm happy if you have a better idea. I had a similar question here when this was introduced.

Thanks, I just wanted to be ensure that's not consensus-related info at that point..

Ideally it shouldn't be in this file, but could came with a better solution later I think. Does it worth to open an issue for (just so as not to forget)?

**Comment by 5chdn** [comment]
@fckt yes

**Pull request merged**
