### PR TITLE
Registry validator set

### PR DESCRIPTION
**Pull request by keorn**

### CODE REVIEW

**Comment by gavofyork** [comment]
don't quite see what this is trying to do...

**Comment by keorn** [comment]
It always uses the address under `validator_set` in registry as the validator contract. This makes it possible to swap the contract out when the registry entry changes.

**Comment by gavofyork** [comment]
don't need this now, right?

**Comment by keorn** [comment]
Does no harm though and may be pretty convenient for experimentation.

**Comment by gavofyork** [comment]
will need resolving

**Comment by gavofyork** [comment]
@rphmeier is this going to significantly hamper your efforts to refactor ready for warp sync?

**Comment by rphmeier** [comment]
Probably not, but would prefer to ice it until warp-friendly engine changes are in.

**Comment by rphmeier** [comment]
With `ReturnDataCopy` we can put forth a pretty simple "ForwardedValidatorSet" ABI that is easily used for sets like this one. Note that changes do have to be directly triggered and finalized for consensus to remain possible.

**Comment by debris** [comment]
This pr hasn't been updated for > 28 days and I'm closing it as a part of pull request cleanup. If it's still relevant, please rebase and reopen it.

**Pull request closed without merging**
