### PR TITLE
Add ECIP1017 to Morden config

### PR DESCRIPTION
**Pull request by whilei**
Uses era length of 2M blocks.

See https://github.com/ethereumproject/go-ethereum/blob/master/core/config/morden.json#L110 for congruent implementation in geth classic.

### CODE REVIEW

**Comment by whilei** [comment]
[clabot:check]

**Comment by 5chdn** [comment]
lgtm, do you mind also updating the bootnodes? https://github.com/ethereumproject/go-ethereum/blob/master/core/config/morden.json#L129-L135

had issues connecting to morden recently.

**Comment by whilei** [comment]
Happy to -- I guess you mean for me to include unique nodes from https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/morden.json#L52-L56?

**Comment by 5chdn** [comment]
No, I meant what I have written, to get working Morden boot nodes from Go-Etc. :-p

**Comment by whilei** [comment]
Oh... wait, you mean updating the _Parity_ bootnodes?

**Comment by 5chdn** [comment]
tests fail. what's causing this? cc @paritytech/ci 

    ./scripts/validate_chainspecs.sh: 7: ./scripts/validate_chainspecs.sh: ./target/release/chainspec: not found

**Comment by whilei** [comment]
I need to order a bumper sticker for my car: `A7-looksgoodtestsfail`

**Pull request merged**
