### PR TITLE
Convert from elasticarray to smallvec

### PR DESCRIPTION
**Pull request by nipunn1313**
Reviving the effort from #1957

- Convert RLP
- Convert KVDB
- Take advantage of smallvec extend
- Add FromSlice trait for compatibility.

Concerns
- SmallVec doesn't support from_slice ergonomically (have to construct an empty and use extend_from_slice). Added a FromSlice trait to make this neater, but could be something worth upstreaming.
- heap_size_of_children (HeapSizeOf) trait not implemented for SmallVec. Maybe we can  upstream this to SmallVec?
- How to run benchmarks before/after?

### CODE REVIEW

**Comment by rphmeier** [comment]
Hey, thanks for reviving this.

> Added a FromSlice trait to make this neater, but could be something worth upstreaming.
Yep, absolutely. Elastic array had the same issue, but it only really bites in a couple places so it's not too bad.

> heap_size_of_children (HeapSizeOf) trait not implemented for SmallVec
This would also definitely be good to upstream so our journaldb heapsize calculations can be just about accurate.

> How to run benchmarks before/after?
`rustup run nightly cargo bench -p ethcore-util rlp` should do it. Also worth taking a look at https://github.com/BurntSushi/cargo-benchcmp to do the comparison.

**Comment by debris** [comment]
I run benchmarks, results are so so 


- **master**

```
test bench_decode_nested_empty_lists ... bench:         403 ns/iter (+/- 131)
test bench_decode_u256_value         ... bench:          96 ns/iter (+/- 55)
test bench_decode_u64_value          ... bench:          38 ns/iter (+/- 3)
test bench_stream_1000_empty_lists   ... bench:       9,839 ns/iter (+/- 1,207)
test bench_stream_nested_empty_lists ... bench:         223 ns/iter (+/- 23)
test bench_stream_u256_value         ... bench:         453 ns/iter (+/- 52)
test bench_stream_u64_value          ... bench:         119 ns/iter (+/- 16)

test trie_insertions_32_mir_1k      ... bench:   2,809,646 ns/iter (+/- 327,858)
test trie_insertions_32_ran_1k      ... bench:   2,798,021 ns/iter (+/- 684,951)
test trie_insertions_random_mid     ... bench:   2,248,365 ns/iter (+/- 668,305)
test trie_insertions_six_high       ... bench:   2,158,090 ns/iter (+/- 293,270)
test trie_insertions_six_low        ... bench:   4,376,365 ns/iter (+/- 582,900)
test trie_insertions_six_mid        ... bench:   2,865,934 ns/iter (+/- 275,838)
test trie_iter                      ... bench:   3,360,379 ns/iter (+/- 1,179,577)
test triehash_insertions_32_mir_1k  ... bench:   1,611,333 ns/iter (+/- 333,457)
test triehash_insertions_32_ran_1k  ... bench:   1,579,652 ns/iter (+/- 245,390)
test triehash_insertions_random_mid ... bench:     961,726 ns/iter (+/- 151,563)
test triehash_insertions_six_high   ... bench:   1,178,401 ns/iter (+/- 318,431)
test triehash_insertions_six_low    ... bench:   1,723,549 ns/iter (+/- 580,936)
test triehash_insertions_six_mid    ... bench:   1,323,567 ns/iter (+/- 279,899)
```

- **nipunn1313:rlp**

```
test bench_decode_nested_empty_lists ... bench:         428 ns/iter (+/- 75)
test bench_decode_u256_value         ... bench:          98 ns/iter (+/- 19)
test bench_decode_u64_value          ... bench:          43 ns/iter (+/- 7)
test bench_stream_1000_empty_lists   ... bench:       7,498 ns/iter (+/- 1,947)
test bench_stream_nested_empty_lists ... bench:         205 ns/iter (+/- 34)
test bench_stream_u256_value         ... bench:         538 ns/iter (+/- 194)
test bench_stream_u64_value          ... bench:         144 ns/iter (+/- 23)

test trie_insertions_32_mir_1k      ... bench:   3,280,926 ns/iter (+/- 449,824)
test trie_insertions_32_ran_1k      ... bench:   3,491,309 ns/iter (+/- 908,917)
test trie_insertions_random_mid     ... bench:   2,531,041 ns/iter (+/- 422,683)
test trie_insertions_six_high       ... bench:   2,413,439 ns/iter (+/- 334,786)
test trie_insertions_six_low        ... bench:   5,144,284 ns/iter (+/- 1,155,198)
test trie_insertions_six_mid        ... bench:   3,501,447 ns/iter (+/- 1,161,870)
test trie_iter                      ... bench:  10,770,659 ns/iter (+/- 2,486,670)
test triehash_insertions_32_mir_1k  ... bench:   2,288,869 ns/iter (+/- 490,656)
test triehash_insertions_32_ran_1k  ... bench:   2,100,589 ns/iter (+/- 469,025)
test triehash_insertions_random_mid ... bench:   1,186,604 ns/iter (+/- 130,369)
test triehash_insertions_six_high   ... bench:   1,434,019 ns/iter (+/- 281,379)
test triehash_insertions_six_low    ... bench:   2,273,912 ns/iter (+/- 602,994)
```

Single integers serialization is **15-20% slower** and what's more important `trie_iter` is **3x slower** than on master

**Comment by nipunn1313** [comment]
Submitted https://github.com/servo/rust-smallvec/pull/42/files for the HeapSizeOf stuff.
Thanks for running the benchmarks. I agree they're disappointing. I think there are a few places we're using extend() instead of extend_from_slice. It's also possible that upping the Node stack portion from 36 to 64 was bad, though I don't understand the usage pattern enough to know for sure. Trying to add 36 back upstream to smallvec so we can remove that variable from the equation.

**Comment by nipunn1313** [comment]
I rebased and used the latest smallvec, but there is still a perf regression (around 2x on the trie_iter). I believe it has to do with unnecessary copies happening during the "Clone" process, though some further profiling is required to know for sure.

Don't recommend landing in this state because of perf. The code ergonomics of the conversion are acceptable now.

**Comment by 5chdn** [comment]
Is this still being worked on?

**Comment by nipunn1313** [comment]
Yes. Albeit slowly (I'm putting spare time into it). If this is of importance/urgency to you folks, feel free to let me know and commandeer the code, but otherwise, I'll keep working on it.

**Comment by debris** [comment]
I'm closing the pr. @nipunn1313 feel free to reopen it when you finish :)

**Pull request closed without merging**
