### PR TITLE
Add test for ethstore-cli, fixes #8027

### LINKED ISSUE #8027: add tests for ethstore-cli
to avoid issues like #8026

### PR DESCRIPTION
**Pull request by izgzhen**
more or less a WIP, any comments? @debris

### CODE REVIEW

**Comment by izgzhen** [comment]
[clabot:check]

**Comment by debris** [comment]
looks good so far :)

**Comment by izgzhen** [comment]
I've addressed the problem of `sign` addressed in issue, and pulled in others that I understood as much as my time permits. You may start review this PR now @debris :)

**Comment by izgzhen** [comment]
```
error: the crate `serde` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`

error: the crate `time` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`

error: the crate `libc` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`

error: aborting due to 3 previous errors

   Compiling fixed-hash v0.1.3
   Compiling elastic-array v0.9.0
error: Could not compile `parity-version`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I have no idea what caused this...

**Comment by debris** [comment]
restarted the build ;)

**Comment by debris** [comment]
forked the branch and reopened the pr. hopefully it will resolve CI cache issues...

**Pull request closed without merging**
