### PR TITLE
.gitlab-ci clean-up #4226

### PR DESCRIPTION
**Pull request by AyushyaChitransh**
This pull request refers to Issue of .gitlab-ci clean-up #4226

### CODE REVIEW

**Comment by AyushyaChitransh** [comment]
[clabot:check]

**Comment by 5chdn** [comment]
Both tests failing.

**Comment by AyushyaChitransh** [comment]
There are some problems with the script for windows. I will try to get this done by tomorrow.

**Comment by 5chdn** [comment]
@paritytech/ci ^

**Comment by arkpar** [comment]
Will get merged after 1.8 release. Still needs a review from @General-Beck or someone from @paritytech/ci

**Comment by General-Beck** [comment]
after 1.8

**Comment by 5chdn** [comment]
hey @General-Beck if you have time, could you have a look? thanks.

**Comment by 5chdn** [comment]
Two tests fail. Windows:

	$ chmod +x ./scripts/gitlab-ci.sh
	'chmod' is not recognized as an internal or external command,
	operable program or batch file.
	ERROR: Job failed: exit status 9009

And Push-Release:

	Running with gitlab-ci-multi-runner 9.5.1 (96b34cc)
	  on cepheus-docker (8df025c2)
	Using Docker executor with image parity/rust:gitlab-ci ...
	ERROR: Preparation failed: Error: No such image: gitlab/gitlab-runner-helper:x86_64-96b34cc
	Will be retried in 3s ...
	Using Docker executor with image parity/rust:gitlab-ci ...
	ERROR: Preparation failed: Error: No such image: gitlab/gitlab-runner-helper:x86_64-96b34cc
	Will be retried in 3s ...
	Using Docker executor with image parity/rust:gitlab-ci ...
	ERROR: Preparation failed: Error: No such image: gitlab/gitlab-runner-helper:x86_64-96b34cc
	Will be retried in 3s ...
	ERROR: Job failed (system failure): Error: No such image: gitlab/gitlab-runner-helper:x86_64-96b34cc

**Comment by General-Beck** [comment]
I'm working on it. several errors.

**Comment by debris** [comment]
any update on it?

**Comment by debris** [comment]
I like the pr a lot, but due to inactivity I'm closing it. Feel free to reopen when it's ready.
cc @AyushyaChitransh @paritytech/ci

**Comment by AyushyaChitransh** [comment]
There shall be a new PR at about the end of this weekend! The scripts in this PR were outdated, and some builds were also failing. Hope that new PR would be better than this one! :smile:

**Comment by 5chdn** [comment]
maybe @paritytech/ci can comment what's required to get this merged. no need to waste the time of our contributors.

**Pull request closed without merging**
