### PR TITLE
Clear explanation on how to make changes to the UI

### PR DESCRIPTION
**Pull request by GregTheGreek**
While playing around with Parity, I noticed it was inherently not straightforward to modify the UI. After some digging, I discovered how the system works and thought it would be very helpful for users to know the underworkings of the UI in Parity.

### CODE REVIEW

**Comment by GregTheGreek** [comment]
[clabot:check]

**Comment by Tbaut** [comment]
Hey @GregTheGreek, I believe this kind of info would be good to have in the FAQ section of the wiki (FAQ: Building, Installation, and Testing) rather than here. Can you please move it there ?

**Comment by folsen** [comment]
@GregTheGreek we're currently working on making the UI its own standalone repo specifically for this purpose, making it easier for people to contribute without having to bring along the whole requirement of "dealing with" the Rust code. Please stay tuned and help us review our explanations on how to get it running there as well :)

**Comment by amaurymartiny** [comment]
@GregTheGreek The standalone github @folsen is talking about is here: https://github.com/Parity-JS. There's a small README in the `shell` repo, but it could definitely be improved. Any help to improve the READMEs or to contribute to the wiki would be greatly appreciated.

I'll close this PR.

**Pull request closed without merging**
