### PR TITLE
Tiny fix in parity.js README.md

### LINKED ISSUE #6536: parity.js : unable to properly deploy a contract
I'm running:
- **Parity version**: Parity/v1.8.0-unstable-b731ccea1-20170903/x86_64-linux-gnu/rustc1.19.0
- **Operating system**:  Linux
- **And installed**: via `pacman -S parity-git`
- **parity.js** installed via `npm i @parity/parity.js`

---

I want to deploy a small contract using `parity.js`, but I ran into a snag.
Perhaps I am using the library incorrectly?

What I tried:
```js
// adapted from the README.md
const Api = require('@parity/parity.js').Api;
const transport = new Api.Transport.Http('http://localhost:8545');
const api = new Api(transport);
const abi = [{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}] // from a small contract
const bcode = '6060604 ... a0029' // large bytecode string
const contract = new api.newContract(abi);
contract.deploy({data: bcode});
```

Expected result: Contract deployed on Kovan network.

Actual result:

```
TypeError: Cannot read property 'estimateGas' of undefined
    at t.value (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:101529)
    at t.value (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:101842)
    at repl:1:10
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
```

Is it possible that this arises from [this function](https://github.com/paritytech/parity/blob/master/js/src/api/contract/contract.js#L100-L108)?

Investigating manually, it seems like `contract._api` is undefined, so maybe it was not set in the constructor.

### PR DESCRIPTION
**Pull request by travs**
Should resolve #6536 (original issue, not the comment).

### CODE REVIEW

**Comment by travs** [comment]
[clabot:check]

**Comment by gavofyork** [comment]
[clabot:check]

**Comment by 5chdn** [comment]
Tests failing probably due to #6536

**Comment by travs** [comment]
with @tomusdrw : moved to PR in [parity.js repo](https://github.com/paritytech/parity.js/pull/3)
Closing this one here

**Pull request closed without merging**
