### PR TITLE
On-chain ACL checker for secretstore

### PR DESCRIPTION
**Pull request by svyatonik**
on top of #4974 
@keorn as agreed yesterday - here's the chain-based AclChecker prototype. Are you going to develop the contract itself? I'll need a contract ABI to generate something like this:
https://github.com/paritytech/parity/blob/master/ethcore/src/miner/service_transaction_checker.rs#L58
Also - are we going to deploy registry contract && get ACL checker contract address from there, or would it be hardcoded/cli-option address?

### CODE REVIEW

**Comment by gavofyork** [comment]
would prefer to have the registry throughout.

**Comment by svyatonik** [comment]
Checked success && failure cases on Kovan

**Comment by rphmeier** [comment]
LGTM; I wonder if we could put the contract into the `native_contracts` crate at some point?

**Comment by svyatonik** [comment]
I thought about it, but as I understand it is for 'core' functionality, while this one is secretstore-specific && secretstore itself is very specific. So do not know if this is a good idea to.
Maybe it would be better to use macros from `native_contracts` to generate this file?

**Comment by gavofyork** [comment]
i think it's fine to have in there. it's not a huge maintenance burden and it's super convenient.

**Comment by svyatonik** [comment]
ok, will move there

**Comment by svyatonik** [comment]
done

**Comment by rphmeier** [comment]
> it is for 'core' functionality

I meant it to be a bin for all contracts we use from Parity (which I suppose includes this)

**Comment by svyatonik** [comment]
Ok, got it :) I thought that, because it doesn't include updater contract. But I suppose it is in TODO list.

**Pull request merged**
