### PR TITLE
Whisper js

### PR DESCRIPTION
**Pull request by kaikun213**
Shh api.
Subscriptions are missing.(method not found -> rpc)

### CODE REVIEW

**Comment by kaikun213** [comment]
[clabot:check]

**Comment by rphmeier** [comment]
Subscriptions should be fixed upon https://github.com/paritytech/parity/pull/6162

**Comment by jacogr** [comment]
We need the functions added to jsonrpc as well. (docs)

**Comment by rphmeier** [comment]
@jacogr https://github.com/paritytech/parity/wiki/JSONRPC-shh-Module

**Comment by jacogr** [comment]
CI not passing.

**Pull request merged**
