### PR TITLE
2 tiny modification on snapshot

### PR DESCRIPTION
**Pull request by EighteenZi**
modify the output info.

### CODE REVIEW

**Comment by EighteenZi** [comment]
I just modified 2 output sentence, maybe the CI error is not on my modification.

**Comment by dvdplm** [comment]
> CI error

I re-ran the job and it still fails at the same test. Locally tests run green I presume?

**Comment by niklasad1** [comment]
I'm pretty sure that the `CI failure` is unrelated to this PR as these changes are `_only_` rust log specific.

I suspect that this is related to #8537, /cc @tomaka, @tomusdrw ?!

**Comment by niklasad1** [comment]
@EighteenZi Can you rebase/merge to master? Then I think the tests will pass as #8602 is merged!

**Pull request merged**
