### PR TITLE
[beta] Backports

### PR DESCRIPTION
**Pull request by andresilva**
- [ ] ~~#8790 devp2p: Move UDP socket handling from Discovery to Host.~~
- [x] #8457 `duration_ns: u64 -> duration: Duration`
- [x] #8524 Keep all enacted blocks notify in order
- [x] #8796 Handle removed logs in filter changes and add geth compatibility field
- [x] #8803 Fixed AuthorityRound deadlock on shutdown
- [x] #8821 Specify critical release flag per network (via #8856)
- [x] #8822 CI: Fix docker tags
- [x] #8832 ethcore: fix ancient block import error handling
- [x] #8834 Disable parallel verification and skip verifiying already imported txs.
- [x] #8854 Fix concurrent access to signer queue
- [x] #8867 Don't allocate in expect_valid_rlp unless necessary
- [x] #8876 update jsonrpc libs, fixed ipc leak
- [x] #8886 Add new ovh bootnodes and fix port for foundation bootnode 3.2
- [x] #8891 Block 0 is valid in queries
- [x] #8892 Add ETC Cooperative-run load balanced parity-based bootnode
- [x] #8906 Minor fix in chain supplier and light provider
- [x] #8853 Check whether we need resealing in miner and unwrap has_account in account_provider
- [x] #8882 Allow disabling local-by-default for transactions with new config entry

### CODE REVIEW

**Comment by andresilva** [comment]
Added #8524 which was missing the `patch` label and #8457 as a precursor to it.

**Comment by andresilva** [comment]
Added #8853, needed for #8882.

**Comment by 5chdn** [comment]
Test fails:

```
failures:

---- v1::tests::mocked::signing::should_check_status_of_request_when_its_resolved stdout ----
	thread 'v1::tests::mocked::signing::should_check_status_of_request_when_its_resolved' panicked at 'assertion failed: `(left == right)` (left: `Some("{\"jsonrpc\":\"2.0\",\"result\":null,\"id\":1}")`, right: `Some("{\"jsonrpc\":\"2.0\",\"result\":\"0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001\",\"id\":1}")`, diff: ` Some("{\"jsonrpc\":\"2.0\",\"result\":null,\"id\":1}") Some("{\"jsonrpc\":\"2.0\",\"result\":\"0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001\",\"id\":1}") `)', rpc/src/v1/tests/mocked/signing.rs:208:2
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:217
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: parity_rpc::v1::tests::mocked::signing::should_check_status_of_request_when_its_resolved
   7: core::ops::function::FnOnce::call_once
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:784
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102


failures:
    v1::tests::mocked::signing::should_check_status_of_request_when_its_resolved

test result: FAILED. 286 passed; 1 failed; 4 ignored; 0 measured; 0 filtered out
```

**Comment by 5chdn** [comment]
Nvm.

**Pull request merged**
