### PR TITLE
Add missing CSP for web3.site

### PR DESCRIPTION
**Pull request by tomusdrw**
cc @kaikun213

### CODE REVIEW

**Comment by gavofyork** [comment]
will need resolving and @kaikun213 please take a look.

**Comment by kaikun213** [comment]
Tested it and it works fine and from my small rust knowledge the code looks good. Only request left is that we enable port 3000 too e.g. when parity is run with `--no-ui-validation` flag. (Disable CSP)

**Comment by gavofyork** [comment]
ok - will leave that to @tomusdrw then

**Comment by tomusdrw** [comment]
@kaikun213 updated!

**Pull request merged**
