### PR TITLE
 Add MCIP-6 Byzyantium transition to Musicoin spec

### PR DESCRIPTION
**Pull request by 5chdn**
Byzantium fork for Musicoin at 2_222_222

As per ? https://github.com/Musicoin/MCIPs/blob/master/MCIPS/mcip-6.md

### CODE REVIEW

**Comment by 5chdn** [comment]
So how to test this: Run `parity --chain ./ethcore/res/ethereum/mcip6_byz.json`

This will connect to a Go client with the same ruleset. If it syncs beyond 42 without error, it should be fine.

**Comment by andresilva** [comment]
I was triggered by the inconsistent formatting in all of our JSON files 🤪

**Comment by 5chdn** [comment]
Yeah, but I don't want to start a tab versus spaces discussion lol. I think 2 spaces are appropriate for JSON.

**Comment by andresilva** [comment]
I agree with you 😉

**Comment by Serpent6877** [comment]
Parity 1.9.5:

2018-03-27 20:03:47  Imported #2222221 254f<80>�eefe (56 txs, 1.27 Mgas, 19.45 ms, 6.76 KiB)
2018-03-27 20:03:55    60/75 peers    284 MiB chain  530 MiB db  0 bytes queue   50 KiB sync  RPC:  0 conn, 14 req/s, 168 µs
2018-03-27 20:04:03  Stage 5 block verification failed for #2222222 (30aa<80>�64d0)
Error: Block(InvalidStateRoot(Mismatch { expected: d199b42b9300724ad167b5cb833ef8c30130b1bea934f2567eb0dd3d726aafa3, found: 03251ca4c49fb78326786a71fa62f201e93ea5b767288b2b4c714d4444cc0731 }))
2018-03-27 20:04:07  Stage 3 block verification failed for #2222222 (1da5<80>�3fa2)
Error: Block(InvalidDifficulty(Mismatch { expected: 9268325972822, found: 9268327021398 }))
2018-03-27 20:04:30    14/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 111 µs
2018-03-27 20:05:05    14/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 175 µs
2018-03-27 20:05:40    17/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 17 req/s, 118 µs
2018-03-27 20:06:15    14/75 peers    284 MiB chain  530 MiB db  0 bytes queue   38 KiB sync  RPC:  0 conn, 16 req/s, 143 µs
2018-03-27 20:06:50    14/75 peers    284 MiB chain  530 MiB db  0 bytes queue   49 KiB sync  RPC:  0 conn, 16 req/s, 166 µs
2018-03-27 20:07:25    11/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 171 µs
2018-03-27 20:08:00     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 15 req/s, 149 µs
2018-03-27 20:08:35    21/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 184 µs
2018-03-27 20:08:41  Imported #2222222 f86b<80>�a476 (48 txs, 4.47 Mgas, 18.88 ms, 18.61 KiB)
2018-03-27 20:09:10     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   38 KiB sync  RPC:  0 conn, 16 req/s, 174 µs
2018-03-27 20:09:30  Imported #2222223 51ef<80>�fd93 (10 txs, 0.24 Mgas, 7.52 ms, 1.66 KiB)
2018-03-27 20:09:45     8/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 183 µs
2018-03-27 20:10:20     8/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 162 µs
2018-03-27 20:10:55     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 162 µs
2018-03-27 20:11:30     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 15 req/s, 148 µs
2018-03-27 20:12:05     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 168 µs
2018-03-27 20:12:40     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 15 req/s, 172 µs
2018-03-27 20:13:15     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 145 µs
2018-03-27 20:13:50    11/75 peers    284 MiB chain  530 MiB db  0 bytes queue   38 KiB sync  RPC:  0 conn, 16 req/s, 163 µs
2018-03-27 20:13:50  Imported #2222224 bfb1<80>�8095 (167 txs, 4.62 Mgas, 45.40 ms, 19.70 KiB)
2018-03-27 20:14:25    11/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 179 µs
2018-03-27 20:15:00    10/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 130 µs
2018-03-27 20:15:17  Imported #2222225 bc4a<80>�45cc (0 txs, 0.00 Mgas, 2.70 ms, 0.50 KiB)
2018-03-27 20:15:35    10/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 149 µs
2018-03-27 20:16:10    11/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 15 req/s, 156 µs
2018-03-27 20:16:16  Imported #2222226 3d56<80>�6e9d (6 txs, 3.51 Mgas, 4.75 ms, 13.92 KiB)
2018-03-27 20:16:44  Imported #2222227 040d<80>�a1f1 (132 txs, 2.82 Mgas, 27.67 ms, 15.68 KiB)
2018-03-27 20:16:45     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 16 req/s, 167 µs
2018-03-27 20:17:20     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 152 µs
2018-03-27 20:17:55     9/75 peers    284 MiB chain  530 MiB db  0 bytes queue   37 KiB sync  RPC:  0 conn, 16 req/s, 134 µs
2018-03-27 20:18:08  Imported #2222228 c28f<80>�700b (0 txs, 0.00 Mgas, 3.02 ms, 0.50 KiB)
2018-03-27 20:18:30    11/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 150 µs
2018-03-27 20:19:05    10/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 16 req/s, 135 µs
2018-03-27 20:19:40     6/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 155 µs
2018-03-27 20:20:00  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    7/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 146 µs
2018-03-27 20:20:30  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    6/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 157 µs
2018-03-27 20:20:40  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    7/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 147 µs
2018-03-27 20:21:05  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    7/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 16 req/s, 154 µs
2018-03-27 20:21:30  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    6/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 166 µs
2018-03-27 20:22:00  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    7/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 154 µs
2018-03-27 20:22:25  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    6/75 peers    284 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 164 µs
2018-03-27 20:22:50  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    7/75 peers    290 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 130 µs
2018-03-27 20:23:00  Syncing #2222228 c28f<80>�700b     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #2222101    8/75 peers    300 MiB chain  530 MiB db  0 bytes queue   48 KiB sync  RPC:  0 conn, 15 req/s, 134 µs


Continues to just Sync every block. Going to kill the DB and restart.

**Pull request merged**
