### PR TITLE
Update Settings/Proxy view to match entries in proxy.pac

### PR DESCRIPTION
**Pull request by bjornwgnr**
Replaces 'home.parity' with 'parity.web3.site' in Settings/Proxy view

### CODE REVIEW

**Comment by gavofyork** [comment]
not actually true any more - we bought web3.site so it all just works, as long as they go to 8081. the entire proxy.pac thing needs removing completely.

**Comment by tomusdrw** [comment]
Sort of. If we switch to support only domain-based access using `proxy.pac` will be necessary to easily support remote-accesed nodes (other options include altering `/etc/hosts` file or setting up local DNS entry).

I would keep it for now and re-visit that when #4474 is being done.

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by debris** [comment]
@tomusdrw any update on this?

**Comment by tomusdrw** [comment]
The page is still there and proxy.pac is still supported so best to update it.

**Pull request merged**
