### PR TITLE
Remove the time dependency where possible

### PR DESCRIPTION
**Pull request by tomaka**
cc #7915 

The `time` crate is no longer maintained. This PR replaces it with `std::time` where possible. Wherever `strftime` is used, the `time` dependency has been kept because there is no straight-forward replacement yet.

In addition to being IMO a positive change, this should also help compile for wasm.

The logic of the code has been preserved, except in a few places where initializing a `u64` to `0` has been replaced with initializing an `Instant` to `Instant::now()`. Since the `0` was mostly a place-holder (similar to `None`), the behaviour should be exactly the same in the end.

### CODE REVIEW

**Comment by tomaka** [comment]
Note that in the future when `const fns` are stable, we should replace the various `u64` constants with `Duration` constants.

**Comment by tomaka** [comment]
After this PR, `time` is used in the following places:

- In `hyper` and related crates ; hyper will probably be stripped down for the client light, because we don't need anything HTTP-related.
- `ethstore` because it requires `strftime` to generale file names. It should be possible to tweak something for wasm here.
- `zip` (and `msdos_time`) ; used only by the `dapps` crate which we don't need for the light-client-in-the-browser objective.
- `node_health` (and its dependency `ntp`) and `logger` because they require `strftime`. This is probably the hardest one to fix.
- `rust-crypto` ; I should be able to submit a PR there.
- `transient-hashmap` ; I should be able to submit a PR there.
- `vergen` ; but it's only used as a build-dependency so it's not a problem.

**Comment by tomaka** [comment]
I just realized that `std::time::Instant` is *not* steady, so replacing `SteadyTime` with `Instant` could be wrong. However considering that it's only about caching and network timeouts, I don't think that we actually need steady clocks.

**Comment by niklasad1** [comment]
@tomaka 
What about [std::time::SystemTime](https://doc.rust-lang.org/std/time/struct.SystemTime.html) it is not monotonically increasing but steady I think.

**Pull request merged**
