### PR TITLE
Cleanup Ellaism bootnodes

### PR DESCRIPTION
**Pull request by ellaismer**
Removed several bootnodes known not to be running anymore. Added two new ones.

### CODE REVIEW

**Comment by ellaismer** [comment]
@5chdn That's weird. Most of those bootnodes are actual peers, and I'm able to use them to successfully sync the network. It might be that some peers are full so they reject new peers. And how did you test whether they're working?

**Comment by 5chdn** [comment]
```bash
$ parity --chain ./ellaism.json --reserved-peers ./ellaism.peer --reserved-only                                                                                                                               
```

with [ellaism.json](https://github.com/ellaismer/parity/blob/bdc159bd23737493b674ad830782f0fb3fe20bde/ethcore/res/ethereum/ellaism.json) and where `ellaism.peer` contains the bootnodes

**Comment by 5chdn** [comment]
maybe you should increase the max-peers of the bootnodes?

**Comment by ellaismer** [comment]
I checked bootnodes that I have control (the first three). None of them reached max-peers.

There're some nodes there I need to run an older Parity version (v1.6.10), would that be an issue?

**Comment by 5chdn** [comment]
It's working well if I drop the reserved-only option, so I'm fine with merging this.

**Pull request merged**
