### PR TITLE
hacktoberfest 

### PR DESCRIPTION
**Pull request by danieldevofficial**

### CODE REVIEW

**Comment by 3esmit** [comment]
?

**Comment by carakas** [comment]
is a spammer for hacktoberfest, you should add the label invalid and just close the pr without merging it

**Comment by 5chdn** [comment]
Only merged issues are counted towards hacktoberfest though. There is no point in spamming non-sense pull-requests.

**Comment by carakas** [comment]
Not true, merge request don't need to merged, only created

**Comment by 5chdn** [comment]
Ouch, that sucks.

**Comment by carakas** [comment]
you can keep them from counting by adding the label `invalid`

**Pull request closed without merging**
