### PR TITLE
Reduce usd_per_tx

### PR DESCRIPTION
**Pull request by MysticRyuujin**
Currently the default minimum transaction fee is .0025 however, a huge amount of transactions are falling below this default minimum. I don't feel like it's Parity's duty to set a default minimum transaction fee, especially when that default is about 4x higher than what [ETH Gas Station](https://ethgasstation.info/) calls the "Safe Low" for a transaction.

While any number of arguments can be made for what a reasonable transaction fee should be, I don't think the place to decide that is in the default configuration...

I've submitted this pull request as a place to have that discussion 😄

---
This change is [Reviewable](https://reviewable.io/reviews/paritytech/parity/7058)

### CODE REVIEW

**Comment by MysticRyuujin** [comment]
[clabot:check]

**Comment by 5chdn** [comment]
I have no objections, really. Just want to say that 0.25 US cents are already cheap. 0.01 US cents is good too. Potential blockchain spammers will use a custom gas price anyways.

**Comment by folsen** [comment]
The only thing I'd be worried about with setting it too low is that in times of high pressure, a lot of transactions will get stuck and we'll get a huge influx of support requests saying "Your application isn't working and my transactions aren't going through."

25c may be too high, 1c is pretty damn low though. Do we have _any_ data at all to say "95% of the time, X would get a transaction through reliably"?

I think the default should be data-driven to as large extent as possible.

**Comment by tomusdrw** [comment]
@folsen Note this setting only affect miners, not regular users of Parity Wallet. The `eth_gasPrice` RPC method is calculating a median gas price from last 100 blocks anyway.

**Comment by 5chdn** [comment]
"Closes" #6973 ;)

**Comment by 5chdn** [comment]
> 25c may be too high, 1c is pretty damn low though. 

Note, it's 0.25c and 0.01c.

> Do we have any data at all to say "95% of the time, X would get a transaction through reliably"?

https://ethgasstation.info/ says;

- `Std Cost for Transfer $0.01` (1.00c)
- `SafeLow Cost for Transfer $0.001` (0.10c)

I don't see why we should default to something 10x lower than the statistical `SafeLow Cost`. Paying a quarter cent for a transaction is perfectly reasonable.

And if any miner disagrees, they can still override it with a custom configuration.

**Comment by MysticRyuujin** [comment]
What? Let's stop changing the decimal places for clarity here...

Currently the default minimum transaction fee is $0.0025
SafeLow Cost for Transfer $0.001

$0.001 < $0.0025

So I don't see why you should default to rejecting transactions that are within the safe low cost by a factor of 2.5x either...

**Comment by 5chdn** [comment]
Reopening for 2nd opinion.

**Comment by tomusdrw** [comment]
The setting will affect network propagation (relaying) of low gas transactions which seems reasonable for me.
The miners are also affected, but they should run with custom settings anyway and set the price according to their own analysis.

That said it should be mentioned in release notes. @MysticRyuujin Would you mind fixing the tests? (don't mind the RpcList, they are not related, just the price needs to be updated).

**Comment by MysticRyuujin** [comment]
@tomusdrw can you point me at which test file(s) need to be updated?

**Comment by 5chdn** [comment]
Now the safe low is 30c. :-p

**Comment by tomusdrw** [comment]
@MysticRyuujin values here needs to be updated:
https://github.com/paritytech/parity/blob/de8d20cea9eab9ab563a7e6314a40bd5432ed26a/parity/params.rs#L229
```
to
```
Calibrated { initial_minimum: 476190464, usd_per_tx: 0.0001, }
```

**Comment by 5chdn** [comment]
Can you fix tests and conflicts?

**Comment by MysticRyuujin** [comment]
So it currently says:
```
initial_minimum: 11904761856u64.into(),
usd_per_tx: 0.0025f32,
```

But I don't know how to convert `Calibrated { initial_minimum: 476190464, usd_per_tx: 0.0001, }` into the proper values to replace the above...

**Comment by rphmeier** [comment]
@MysticRyuujin yes, that would fix it

**Comment by 5chdn** [comment]
Fixed the build but the tests still fail

**Comment by MysticRyuujin** [comment]
Should `476190474u64` be `476190464u64` ?

**Comment by 5chdn** [comment]
Yes sorry

**Pull request merged**
