### PR TITLE
Integrate UI 2

### PR DESCRIPTION
**Pull request by tomusdrw**
Integrates UI-2 as a main Parity Wallet.
v1 of the wallet is still available as a Dapp.

Known issues:
- [ ] Parity Extension does not display the signer (will be done in a separate PR, right now we might re-think how the code is actually referenced)

All kudos to @jacogr  :)

Obviously the whole PR is not reviewable, you might look at some last commits to see how the integration was done.

NOTE: I propose this PR is not merged using "Squash & Merge", specific commits might be useful.

### CODE REVIEW

**Comment by 5chdn** [comment]
To my understanding, it completely replaces the old UI. I propose to merge this rather early and directly start testing nightly builds with this. Not sure how this can be reviewed anyways.

**Comment by 5chdn** [comment]
Test fails with a warning ;)

	error[E0063]: missing field `dapps_address` in initializer of `rpc::WsConfiguration`
	    --> parity/configuration.rs:1310:65
	     |
	1310 | 		assert_eq!(conf.into_command().unwrap().cmd, Cmd::SignerToken(WsConfiguration {
	     | 		                                                              ^^^^^^^^^^^^^^^ missing `dapps_address`

	error: aborting due to previous error

	error: Could not compile `parity`.
	warning: build failed, waiting for other jobs to finish...
	error: build failed
	ERROR: Job failed: exit code 1

**Comment by 5chdn** [comment]
Also, #6818 should go in first unless @jacogr wants to directly point that one to beta.

**Comment by jacogr** [comment]
@5chdn #6818 will merge into the `paritytech/js-shared` repo. (and #6756 in `paritytech/js-ui`)

@tomusdrw I believe it should be "squashed and merged" as per normal - there is a lot of noise in the commits from "merge master into other repos, update the dependencies" - not sure it is useful since as it stands the useful commits get lost in the noise anyway

**Comment by 5chdn** [comment]
Tests are good. Has some conflicts from #6818 

Does this replace #5486 ? Also, do we merge #6756 before this or do we close #6756 ? @jacogr this keeps confusing me :p

**Pull request merged**
