### PR TITLE
bump parking_lot to 0.6

### PR DESCRIPTION
**Pull request by sorpaas**
We still need to update jsonrpc dependency to completely remove parking_lot 0.5. rel https://github.com/paritytech/jsonrpc/pull/285

This also bumps parity-wasm, because of https://github.com/paritytech/parity-wasm/commit/df381c4542fe8ea45557c4964d20560b92e260c2

### CODE REVIEW

**Comment by sorpaas** [comment]
Found out that this will also depend on https://github.com/paritytech/wasmi/pull/105 and https://github.com/paritytech/wasm-utils/pull/90. It's also possible to just update to parity-utils 0.30 and do a bugfix release on wasmi, but I think doing a complete update would save some repeat work.

**Comment by pepyakin** [comment]
[wasmi 0.2.1](https://crates.io/crates/wasmi) and 
[pwasm-utils 0.2.2](https://crates.io/crates/pwasm-utils) is out.

**Comment by 5chdn** [comment]
Restarted CI.

**Comment by 5chdn** [comment]
Restarted CI again :roll_eyes:

**Pull request merged**
