### PR TITLE
Chinese Translation 

### PR DESCRIPTION
**Pull request by btceth**
This Chinese translation, please check it.

### CODE REVIEW

**Comment by gavofyork** [comment]
wow thanks!

**Comment by gavofyork** [comment]
[clabot:check]

**Comment by jacogr** [comment]
Thanks a lot for this, will get it tested and provide feedback.

**Comment by CraigglesO** [comment]
謝謝！ 你來自哪裡？

**Comment by btceth** [comment]
[clabot:check]

**Comment by jacogr** [comment]
Looks good, displays properly, selection works. The infrastructure for this one however (entirely my fault), has been lacking somewhat. I've made a PR () that takes these changes and adds the necessary scaffolding to bring it into the fold.

Next rounds should just be a case of adding the translations of `src/i18n/_default` into the `src/i18n/zh` folder.

parity 2017-03-27 10-15-21
parity 2017-03-27 10-15-43

(Making as looksgoodcantmerge in favour of #5289)

**Comment by jacogr** [comment]
Closing in favour of #5289 (merged).

**Pull request closed without merging**
