### PR TITLE
Update `app_dirs` to 1.2.1

### PR DESCRIPTION
**Pull request by rleungx**
This PR fixes the compiling error with rustc 1.25.0.
`app_dirs2` is a fork of `app_dirs` and it seems that `app_dirs` is no longer maintained.
See #8267.

### CODE REVIEW

**Comment by rleungx** [comment]
[clabot:check]

**Comment by tomusdrw** [comment]
image

Seems that the author woke up, maybe better to just bump the version then?

**Comment by rleungx** [comment]
Sure. I didn't notice that.

**Comment by greysteil** [comment]
Would you be up for automatically generating dependency update PRs like this one (well, without all the work to handle breaking changes)? I built [Dependabot](https://dependabot.com) to try and help people keep their dependencies up-to-date, and just added Rust support. When I ran it on my fork it generated [this PRs](https://github.com/greysteil/parity/pulls).

It's totally free for open source, and always will be - I'm just looking for beta testers and advice. :octocat:

**Pull request merged**
