### PR TITLE
Render Cancel/Edit toggle in Signer for not mined transactions

### PR DESCRIPTION
**Pull request by jacogr**

### CODE REVIEW

**Comment by 5chdn** [comment]
There is no point in merging this into master if we plan to release 1.9 with a new UI, don't you think? Fixes to the old UI could go directly into 1.8...

**Comment by jacogr** [comment]
Don't mind either way, can add it to the paritytech/js-ui repo.

**Comment by 5chdn** [comment]
Just saying, if this does not delay UI-2 I'm cool (>^,^)>

**Comment by gavofyork** [comment]
may as well put it right into 1.8 branch, @5chdn

**Comment by jacogr** [comment]
Going to merge into the `paritytech/js-ui` repo and make a backport for `beta`. (Marking WIP until tose are done and I can close the PR)

**Comment by 5chdn** [comment]
What's the plan for this one? Close and reopen against beta?

**Comment by jacogr** [comment]
It has not dropped off the radar, it is in the queue to address - still need the v2 ports (js-ui repo) and 1.8 port, will close this one when those are available.

**Comment by tomusdrw** [comment]
@jacogr any progress?

**Comment by jacogr** [comment]
Closing, merged into `paritytech/js-ui`

**Pull request closed without merging**
