### PR TITLE
Add skeleton for status api.

### PR DESCRIPTION
**Pull request by adrianbrink**
#4801 

This is the pull request tracking my implementation of the status api.

@tomusdrw : This isn't done yet. I'll update the PR as I get further. :-)

### CODE REVIEW

**Comment by tomusdrw** [comment]
@adrianbrink Looks promising! :) BTW: Make sure to use tabs.

**Comment by rphmeier** [comment]
@adrianbrink As a suggestion, you may want to implement actually getting peer values via a generic method. This will make it easier to set up in tests, easier to support other network implementations than `EthSync` (e.g. the light client), and it won't require bringing in a `sync` crate dependency on `dapps`.

You could do that via a `Box<Fn() -> Vec<i32>>` or a `Box<GetPeerCount>`, where `GetPeerCount` has a function for getting peer count.

**Comment by tomusdrw** [comment]
You can actually make `RestApi` generic, since we `Box` it anyway in `to_handler` method.

**Comment by tomusdrw** [comment]
Closing since there is no progress for a long time and the dapps API has been changed substantially so it will require a merge or a re-write.
@adrianbrink Feel free to create a new PR when it's ready :)

**Pull request closed without merging**
