### PR TITLE
Use cached prime sieve instead of recalculating each time

### PR DESCRIPTION
**Pull request by Vurich**
This is _much_ faster. I don't know how much speed we gain with this alone, but combined with the unrolling work we get down to consistently ~8% below the C implementation (better than before, which was inconsistently around 3% below). A possible improvement would be to use `UnsafeCell`, since doing so would be sound, but benching it shows that aquiring the lock is not a bottleneck (it's not a real lock, after all).

### CODE REVIEW

**Comment by arkpar** [comment]
Would be even faster to cache `data_size`/`cache_size` per epoch

**Comment by Vurich** [comment]
Yeah, this is what `libethash` does. This uses less disk space, though (in theory). If we're going down that path I would rather store the whole set of epoch->`data_size`/`cache_size` in a static array so it gets read from disk instead of RAM. I don't know whether an anonymous memmap would help here too, I _think_ that would write to disk but it might just act like a memmap while actually using RAM. What we essentially want is to force allocation in swap space.

**Comment by arkpar** [comment]
`epoch_number`->`size` is relatively small. Mainnet only has 133 epochs so far and there probably won't be more than 300 before the switch to PoS. As far as I know `memmap` is used for the DAG data, not for the DAG size map. This is an important memory optimization indeed, especially for the light client.

**Comment by Vurich** [comment]
A constant-size solution would be to just store the last-seen one, since it's very common for us to just call this with monotonically-increasing epochs.

**Comment by NikVolf** [comment]
need rebase and @arkpar approval

**Comment by Vurich** [comment]
I think that on balance it might be better to have both this _and_ cached cache/data sizes. Both are relatively small memory costs but this speeds up initial calculation (since getting `is_prime` from a sieve is way faster than getting it using the standalone function) and then cached sizes means that we don't have to recalculate very often. I would say that this could be merged and then we could add a thread-local `MemoryLruCache` for those two functions. That's my two cents though, I'd appreciate feedback from @arkpar

**Comment by arkpar** [comment]
@Vurich agreed.

**Comment by Vurich** [comment]
This is waiting for https://github.com/paritytech/parity/pull/6193 to merge, since this will conflict with that. I'll include both this and the `MemoryLruCache` changes in the new version of the PR.

**Pull request closed without merging**
