### PR TITLE
Fix libssl dependency for deb build script.

### LINKED ISSUE #5893: libssl1.0.0 is not available anymore
Do you plan to migrate to the [libssl 1.1.0f-3](https://packages.debian.org/stretch/libssl-dev) available in newly release debian stable?

### PR DESCRIPTION
**Pull request by 5chdn**
Reverts #4260

Closes #5893

### CODE REVIEW

**Comment by arkpar** [comment]
Does it break compatibility with ubuntu 14.x?

**Comment by 5chdn** [comment]
Not trying to become emotional about this :-p

Just did a quick search, this will break Debian oldstable (Jessie) and _all_ Ubuntu versions. I do not fully understand how it's impossible to ship the 1.1 version of openssl with new Ubuntu versions.

    Ubuntu 14.04 openssl 1.0.1f libssl-dev 1.0.1f
    Ubuntu 16.04 openssl 1.0.2g libssl-dev 1.0.2g
    Ubuntu 17.04 openssl 1.0.2g libssl-dev 1.0.2g
    Ubuntu 17.10 openssl 1.0.2g libssl-dev 1.0.2g

    Debian 08 OldStable   (Jessi) openssl 1.0.1t libssl-dev 1.0.1t
    Debian 09    Stable (Stretch) openssl 1.1.0f libssl-dev 1.1.0f
    Debian 10   Testing  (Buster) openssl 1.1.0f libssl-dev 1.1.0f

Closing because I have no idea how to tackle this. I was assuming that if a dinosaur like debian introduces openssl 1.1, ubuntu would have long been there,

**Comment by 5chdn** [comment]
The only solution that comes to my mind is providing different packages for different linux derivatives and versions. Or move away from debs at all.

**Comment by arkpar** [comment]
Won't something like `libssl1.0.0 (>=1.0.0) | libssl (>=1.1.0)` work?

**Comment by 5chdn** [comment]
No. Well, maybe, but it will get pretty complex. The issue is debian and ubuntu use different naming convention. In Debian 10 it's `libssl1.0.2` for 1.0.2g and in Ubuntu it's `libssl1.0.0` for 1.0.2l. Here is a matrix that displays same packages by name and colors them by different versions:

screenshot at 2017-09-20 11-42-43

With the current configuration, only Debian stable and testing is broken. The following _could_ work (I'm not sure if the syntax allows it):

    libssl (>=1.0.0) | libssl1.0.0 (>=1.0.0) | libssl1.0.2 (>=1.0.0)

But I would need to find a way to test that first.

**Comment by jpritikin** [comment]
Is this merged for parity 1.8? Because I still can't install parity 1.8.

**Comment by 5chdn** [comment]
No, I closed this because this breaks all Ubuntu versions. If you have any idea, please let me know.

**Comment by iFA88** [comment]
If you wish to use parity on Debian 9 ( stretch ) you need download the package from https://packages.debian.org/jessie/libssl1.0.0 and install like `dpkg --install libssl1.0.0_1.0.1t-+deb8u6_amd64.deb` as root. For me works.

**Pull request closed without merging**
