### PR TITLE
Fix deadlock in blockchain.

### PR DESCRIPTION
**Pull request by tomusdrw**
From https://docs.rs/parking_lot/0.6.2/parking_lot/type.RwLock.html

> This lock uses a task-fair locking policy which avoids both reader and writer starvation. This means that readers trying to acquire the lock will block even if the lock is unlocked when there are writers waiting to acquire the lock. Because of this, **attempts to recursively acquire a read lock within a single thread may result in a deadlock.**

And it seems that `first_block_number()` actually goes through `block_number(_)` where we check the `best_block` again

### CODE REVIEW

**Comment by 5chdn** [comment]
Please indicate whether we need to backport this.

**Comment by tomusdrw** [comment]
@5chdn we do, label added.

**Comment by debris** [comment]
When was this bug introduced? It seems like parity should deadlock every time this function is called

**Comment by tomusdrw** [comment]
@debris it deadlocks randomly and only when it happens that there is a `write()` lock request in between the two reads. I think the change was introduced in my header refactoring PR I remember touching some stuff with the `best_block` code.

**Comment by 5chdn** [comment]
Please rebase on latest master to fix CI.

**Pull request merged**
