### PR TITLE
do not activate genesis epoch in immediate transition validator contract

### LINKED ISSUE #6343: Parity 1.7.0 fails to sync with "immediateTransitions": true and 1.6.8 style validator contract
[config.toml.txt](https://github.com/paritytech/parity/files/1238549/config.toml.txt)

[chain-spec.json.txt](https://github.com/paritytech/parity/files/1238547/chain-spec.json.txt)

> I'm running:   Parity POA network with a validator contract that was working OK with 1.6.8
>
> - **Parity version**: 1.7.0
> - **Operating system**:  Linux Ubuntu Xenial
> - **And installed**: via apt-get and source

I am trying to migrate my blockchain created with Parity 1.6.8 over to Parity 1.7.0.
I know that the validator contract ABI changed but am using "immediateTransitions": true as indicated in this bug: https://github.com/paritytech/parity/issues/6190 in order to use the old style contract.

The command I used to run my Parity 1.7.0 is below:
```
parity --no-warp --geth --config /home/parity/.parity/config.toml --no-download -lsync=trace
```
However I get two errors in my log shown below:
```
2017-08-21 11:30:37  IO Worker #0 TRACE sync  New peer 0 (protocol: 2, network: 12345, difficulty: Some(324027023360), latest:ec22…a224, genesis:aa49…2d26, snapshot:Some(2470000))
2017-08-21 11:30:37  IO Worker #0 TRACE sync  Peer 0 genesis hash mismatch (ours: 2dec…d4ae, theirs: aa49…2d26)
2017-08-21 11:30:37  IO Worker #0 TRACE sync  == Disconnecting 0: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-21 11:30:40  IO Worker #3 WARN ethcore::engines::common  Encountered error on making system call: Bad instruction fe
2017-08-21 11:30:41  IO Worker #0 INFO network  Public node URL: enode://1dd33.............60@x.x.x.x:30303
2017-08-21 11:30:45  IO Worker #3 WARN ethcore::engines::common  Encountered error on making system call: Bad instruction fe
2017-08-21 11:30:50  IO Worker #3 WARN ethcore::engines::common  Encountered error on making system call: Bad instruction fe
2017-08-21 11:30:55  IO Worker #3 WARN ethcore::engines::common  Encountered error on making system call: Bad instruction fe
2017-08-21 11:31:00  IO Worker #3 WARN ethcore::engines::common  Encountered error on making system call: Bad instruction fe
2017-08-21 11:31:05  IO Worker #3 WARN ethcore::engines::common  Encountered error on making system call: Bad instruction fe

```

From the above log we see that the genesis hash differs and the new Parity seems to be trying to call the new contract ABI even with the "immediateTransistions" flag set. 

---

### PR DESCRIPTION
**Pull request by rphmeier**
Fixes #6343 

@mills-nick can you try with a build of this PR?

### CODE REVIEW

**Comment by mills-nick** [comment]
@rphmeier Yes, I'll try to reproduce https://github.com/paritytech/parity/issues/6343 with this branch.

**Comment by mills-nick** [comment]
From the logs it looks as though the new validator contract ABI is no longer being called. However we still have a genesis hash mismatch.

```
2017-08-24 02:46:41  main INFO parity::run  Starting Parity/v1.8.0-unstable-2129eda-20170817/x86_64-linux-gnu/rustc1.19.0
2017-08-24 02:46:41  main INFO parity::run  Keys path /home/parity/.parity/keys/GMOPrivateChain
2017-08-24 02:46:41  main INFO parity::run  DB path /home/parity/.parity/chains/GMOPrivateChain/db/c5d6558cf4358f74
2017-08-24 02:46:41  main INFO parity::run  Path to dapps /home/parity/.parity/dapps
2017-08-24 02:46:41  main INFO parity::run  State DB configuration: fast
2017-08-24 02:46:41  main INFO parity::run  Operating mode: active
2017-08-24 02:46:41  main INFO ethcore::service  Configured for GMOPrivateChain using AuthorityRound engine
2017-08-24 02:46:42   INFO miner  Updated conversion rate to Ξ1 = US$317.61 (374823260 wei/gas)
2017-08-24 02:46:42  IO Worker #1 TRACE sync  == Connected 0: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:42  IO Worker #1 TRACE sync  Sending status to 0, protocol version 2
2017-08-24 02:46:42  IO Worker #2 TRACE sync  == Connected 1: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:42  IO Worker #2 TRACE sync  Sending status to 1, protocol version 2
2017-08-24 02:46:42  IO Worker #2 TRACE sync  == Disconnecting 1: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:42  IO Worker #1 TRACE sync  New peer 0 (protocol: 2, network: 12345, difficulty: Some(329997746176), latest:92b1…7483, genesis:aa49…2d26, snapshot:Some(2510000))
2017-08-24 02:46:42  IO Worker #1 TRACE sync  Status packet from expired session 0:Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:42  IO Worker #2 TRACE sync  == Disconnecting 0: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:43  IO Worker #0 TRACE sync  == Connected 30: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:43  IO Worker #0 TRACE sync  Sending status to 30, protocol version 2
2017-08-24 02:46:43  IO Worker #0 TRACE sync  == Connected 29: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:43  IO Worker #0 TRACE sync  Sending status to 29, protocol version 2
2017-08-24 02:46:43  IO Worker #2 TRACE sync  == Disconnecting 30: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:43  IO Worker #2 TRACE sync  New peer 29 (protocol: 2, network: 12345, difficulty: Some(329997746176), latest:92b1…7483, genesis:aa49…2d26, snapshot:Some(2510000))
2017-08-24 02:46:43  IO Worker #2 TRACE sync  Peer 29 genesis hash mismatch (ours: 2dec…d4ae, theirs: aa49…2d26)
2017-08-24 02:46:43  IO Worker #0 TRACE sync  == Disconnecting 29: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:44  IO Worker #1 TRACE sync  == Connected 57: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:44  IO Worker #1 TRACE sync  Sending status to 57, protocol version 2
2017-08-24 02:46:44  IO Worker #0 TRACE sync  == Disconnecting 57: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:45  IO Worker #1 TRACE sync  == Connected 57: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:45  IO Worker #1 TRACE sync  Sending status to 57, protocol version 2
2017-08-24 02:46:45  IO Worker #1 TRACE sync  == Disconnecting 57: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:46  IO Worker #1 INFO network  Public node URL: enode://1dd330b5aa5b08c0dafb94435a92fc7e2166dbdea521c8e44a9bc2df3f53e6a8534a4b9f3c853f299e7a059ec2cf4136c2fb2c6590a8f2dc0251f15f4aab4060@10.0.2.15:30303
2017-08-24 02:46:46  IO Worker #2 TRACE sync  == Connected 57: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:46  IO Worker #2 TRACE sync  Sending status to 57, protocol version 2
2017-08-24 02:46:46  IO Worker #1 TRACE sync  == Disconnecting 57: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:49  IO Worker #2 TRACE sync  == Connected 18: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:49  IO Worker #2 TRACE sync  Sending status to 18, protocol version 2
2017-08-24 02:46:49  IO Worker #0 TRACE sync  == Disconnecting 18: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:49  IO Worker #3 TRACE sync  == Connected 39: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:49  IO Worker #3 TRACE sync  Sending status to 39, protocol version 2
2017-08-24 02:46:49  IO Worker #3 TRACE sync  == Disconnecting 39: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:50  IO Worker #3 TRACE sync  == Connected 10: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:50  IO Worker #3 TRACE sync  Sending status to 10, protocol version 2
2017-08-24 02:46:50  IO Worker #3 TRACE sync  == Disconnecting 10: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:51  IO Worker #1 TRACE sync  == Connected 10: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:51  IO Worker #1 TRACE sync  Sending status to 10, protocol version 2
2017-08-24 02:46:51  IO Worker #2 TRACE sync  == Disconnecting 10: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:52  IO Worker #0 TRACE sync  == Connected 10: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:46:52  IO Worker #0 TRACE sync  Sending status to 10, protocol version 2
2017-08-24 02:46:52  IO Worker #1 TRACE sync  New peer 10 (protocol: 2, network: 12345, difficulty: Some(329998008320), latest:b6a7…77a6, genesis:aa49…2d26, snapshot:Some(2510000))
2017-08-24 02:46:52  IO Worker #1 TRACE sync  Peer 10 genesis hash mismatch (ours: 2dec…d4ae, theirs: aa49…2d26)
2017-08-24 02:46:52  IO Worker #2 TRACE sync  == Disconnecting 10: Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
2017-08-24 02:47:12  IO Worker #1 INFO import     0/25 peers      8 KiB chain   21 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
```

**Comment by mills-nick** [comment]
Is the 1.7.x POA genesis somehow different to earlier version genesis blocks? Because of the epoch data maybe?

**Comment by rphmeier** [comment]
Epoch data isn't actually included in the state, so it shouldn't be different. I'll have to investigate the differences, but AFAIK we haven't made any changes to how the genesis header is computed.

**Comment by mills-nick** [comment]
I think the genesis mismatch is my fault. It seems as though I was using the wrong genesis json! I'll check this again and report back here.

**Comment by mills-nick** [comment]
I double checked my chain-spec.json and it is mostly identical to the chain-spec.json on the network.
With the only differences being that I added "immediateTransitions": true for the authorityRound.params and "gasLimitBoundDivisor": "0x400" for the params sections.

So, the genesis mismatch seems to be a real issue.

**Comment by rphmeier** [comment]
Could you send over your chain spec or at least one which reproduces the issue for testing? I think this may be another issue entirely and should be addressed in another PR

**Comment by mills-nick** [comment]
@rphmeier please refer to the attached chain-spec.json.txt and config.toml.txt files in https://github.com/paritytech/parity/issues/6343 to reproduce the genesis mismatch issue.

**Pull request merged**
