### PR TITLE
remove the deprecated options in rustfmt.toml

### PR DESCRIPTION
**Pull request by guanqun**
The old rustfmt.toml can't work with latest rustfmt. Some of these configs in rustfmt have been either removed or renamed. So updating this file to reflect these changes. This should be a good starting point for our new coding standards in parity.

### CODE REVIEW

**Comment by tomusdrw** [comment]
Awesome! Did you try to run `rustfmt` against the codebase? What are the results?

**Comment by guanqun** [comment]
```
 build.rs                           |   7 +-
 parity/account.rs                  |  26 ++--
 parity/blockchain.rs               | 166 ++++++++-----------------
 parity/boot.rs                     |  50 ++++----
 parity/cache.rs                    |   3 +-
 parity/cli/mod.rs                  | 768 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------
 parity/configuration.rs            | 681 +++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------
 parity/dapps.rs                    |  85 +++++--------
 parity/deprecated.rs               |  78 ++++++------
 parity/dir.rs                      |  59 +++++----
 parity/helpers.rs                  | 139 ++++++++-------------
 parity/informant.rs                |  57 ++++-----
 parity/ipfs.rs                     |  12 +-
 parity/light_helpers/queue_cull.rs |  38 ++++--
 parity/main.rs                     | 104 +++++++++-------
 parity/migration.rs                |  34 +++--
 parity/modules.rs                  | 110 +++++++----------
 parity/params.rs                   |  61 +++++----
 parity/presale.rs                  |   2 +-
 parity/rpc.rs                      |  93 +++++---------
 parity/rpc_apis.rs                 | 297 ++++++++++++++++++++++----------------------
 parity/run.rs                      | 318 ++++++++++++++++++++---------------------------
 parity/secretstore.rs              |  28 ++---
 parity/signer.rs                   |  58 +++------
 parity/snapshot.rs                 | 101 ++++++---------
 parity/stratum.rs                  |  86 +++++--------
 parity/sync.rs                     |  55 +++------
 parity/upgrade.rs                  |  49 ++++----
 parity/url.rs                      |  12 +-
 parity/user_defaults.rs            |  61 +++++----
 30 files changed, 1701 insertions(+), 1937 deletions(-)
```

There are thousands of lines of changes... Do you want me to create a code review for this?

**Comment by guanqun** [comment]
I created another PR here: https://github.com/paritytech/parity/pull/5624

I'd like to get this PR merged, but leave the other one abandoned, unless we agree on a good style. :) 

And looks like our parity is not a workspace yet, so only run fmt on parity, not all submodules.

**Comment by guanqun** [comment]
I closed the other PR and hopefully we can get this small changes merged in.

**Comment by gavofyork** [comment]
looks good! thanks @guanqun !

**Pull request merged**
