### PR TITLE
Add ETC Cooperative-run load balanced parity-based bootnode

### PR DESCRIPTION
**Pull request by pyskell**
As requested by @5chdn. May have more additions/removals in the coming weeks.

### CODE REVIEW

**Comment by pyskell** [comment]
[clabot:check]

**Comment by eosclassicteam** [comment]
@pyskell I wonder how we can also loadbalance geth bootnodes....

**Comment by pyskell** [comment]
@andresilva Just curious, do you have a tool that checks if a node is working or do you just do something like `parity --nodiscover --bootnodes="enode..."`?

**Comment by 5chdn** [comment]
@pyskell `--reserved-only --reserved-nodes file.txt`

**Pull request merged**
