### PR TITLE
Remove redundant `mut`

### PR DESCRIPTION
**Pull request by 0x7CFE**
This PR removes unneeded `mut` specifiers across the codebase.

### CODE REVIEW

**Comment by 0x7CFE** [comment]
In my case the only warnings left are:
```
warning: variable does not need to be mutable
   --> parity/target/release/build/ethcore-ipc-hypervisor-c1a2466723855f8b/out/service.rs.in:764:42
    |
764 |         modules.get_mut(&module_id).map(|mut module|
    |                                          ^^^^^^^^^^
    |
    = note: #[warn(unused_mut)] on by default

warning: variable does not need to be mutable
   --> parity/target/release/build/ethcore-ipc-hypervisor-c1a2466723855f8b/out/service.rs.in:775:42
    |
775 |         modules.get_mut(&module_id).map(|mut module|
    |                                          ^^^^^^^^^^
```

If I understand correctly, these sources are generated automatically. Which file should I edit to remove these warning as well?

**Comment by debris** [comment]
I believe it's `ipc/hypervisor/src/service.rs.in`

**Comment by 0x7CFE** [comment]
Oops, I was submitting final commit 730b80 when you merged the PR :) Should I open another PR for that one?

**Comment by 0x7CFE** [comment]
Final change in https://github.com/paritytech/parity/pull/6775

**Pull request merged**
