### PR TITLE
Get rid of "TraceDB resync required" error message

### PR DESCRIPTION
**Pull request by Neurone**
- `User_defaults` now contains serialization for `is_first_launch` parameter
- Solved the _TraceDB resync required_ error message when trying to use _--tracing on_ option just after a DB kill operation

### CODE REVIEW

**Comment by Neurone** [comment]
[clabot:check]

**Comment by gavofyork** [comment]
build error?

**Comment by arkpar** [comment]
Build error is caused by recent build breakage in master. I can see that all tests were successful though.

**Comment by arkpar** [comment]
@Neurone Thank you for the contribution

**Pull request merged**
